from views import *
from event_detail import *
from events_calendar import *
from archival_calendars import *
from archival_results import *
from archival_info import *
from events_results import *
from events_informations import *
from records import *
from stats import *
